In [1]:
import pathlib
import sys

import ambulance_game as abg

In [2]:
relative_path = pathlib.Path.cwd().parent
sys.path.insert(0, relative_path.as_posix())
from main import (
    get_path_of_experiment,
    get_parameters,
    get_matrices,
    get_lemke_howson_outcome,
    get_fictitious_play_outcome,
    get_stochastic_fictitious_play_outcome,
    get_performance_measure_for_given_strategies,
    find_best_performance_measure,
    find_worst_nash_equilibrium_measure,
    get_price_of_anarchy,
)

# Parameters

In [3]:
parameters = get_parameters()
parameters

{'alpha': 0.35000000000000003,
 'buffer_capacity_1': 1,
 'buffer_capacity_2': 8,
 'lambda_1_1': 0.33202952007732955,
 'lambda_1_2': 21.485754332120408,
 'lambda_2': 0.1,
 'mu_1': 0.42057072543128415,
 'mu_2': 4.8598730036939015,
 'num_of_servers_1': 5,
 'num_of_servers_2': 7,
 'system_capacity_1': 8,
 'system_capacity_2': 7,
 'target': 10.0}

# Matrices

In [4]:
R, A, B = get_matrices()
R

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [1.        , 1.        , 0.29791094, 0.        , 0.        ,
        0.        , 0.        ],
       [1.        , 1.        , 1.        , 1.        , 0.0165745 ,
        0.        , 0.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        0.85855447, 0.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 0.89297584],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ]])

In [5]:
A

array([[-0.00123085, -0.00123085, -0.00123085, -0.00123085, -0.00123085,
        -0.00123085, -0.00123085],
       [-0.00123077, -0.00123077, -0.00123083, -0.00123085, -0.00123085,
        -0.00123085, -0.00123085],
       [-0.00123065, -0.00123065, -0.00123065, -0.00123065, -0.00123085,
        -0.00123085, -0.00123085],
       [-0.00123047, -0.00123047, -0.00123047, -0.00123047, -0.00123047,
        -0.00123053, -0.00123085],
       [-0.00123024, -0.00123024, -0.00123024, -0.00123024, -0.00123024,
        -0.00123024, -0.00123032],
       [-0.00122993, -0.00122993, -0.00122993, -0.00122993, -0.00122993,
        -0.00122993, -0.00122993],
       [-0.00122985, -0.00122985, -0.00122985, -0.00122985, -0.00122985,
        -0.00122985, -0.00122985],
       [-0.00122984, -0.00122984, -0.00122984, -0.00122984, -0.00122984,
        -0.00122984, -0.00122984]])

In [6]:
B

array([[-0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025],
       [-0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025],
       [-0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025],
       [-0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025],
       [-0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025],
       [-0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025],
       [-0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025],
       [-0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025, -0.0025]])

# Lemke - Howson

In [7]:
get_lemke_howson_outcome()

C:\Users\micha\Anaconda3\envs\AmbulanceGame\lib\site-packages\nashpy\integer_pivoting\integer_pivoting.py:31: RuntimeWarning: invalid value encountered in true_divide
  return np.argmax(tableau[:, column_index] / tableau[:, -1])
C:\Users\micha\Anaconda3\envs\AmbulanceGame\lib\site-packages\nashpy\algorithms\lemke_howson.py:61: RuntimeWarning: invalid value encountered in true_divide
  return strategy / sum(strategy)
C:\Users\micha\Anaconda3\envs\AmbulanceGame\lib\site-packages\nashpy\algorithms\lemke_howson.py:132: RuntimeWarning: The Lemke Howson algorithm has returned probability vectors of 
incorrect shapes. This indicates an error. Your game could be degenerate.
  warnings.warn(msg, RuntimeWarning)


RuntimeError: generator raised StopIteration

# Fictitious Play

In [8]:
get_fictitious_play_outcome(iterations=1000, repetitions=10)

((array([0.   , 0.001, 0.   , 0.   , 0.   , 0.   , 0.   , 0.999]),
  array([0.   , 0.379, 0.   , 0.   , 0.248, 0.   , 0.373])),
 (array([0.   , 0.   , 0.   , 0.   , 0.001, 0.   , 0.   , 0.999]),
  array([0.   , 0.372, 0.   , 0.   , 0.376, 0.   , 0.252])),
 (array([0.001, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.999]),
  array([0.001, 0.248, 0.   , 0.001, 0.262, 0.   , 0.488])))

# Stochastic Fictitious Play

In [9]:
get_stochastic_fictitious_play_outcome(iterations=1000, repetitions=10)

([array([0.12585992, 0.12519471, 0.12216786, 0.12871297, 0.12309844,
         0.1262707 , 0.12666663, 0.12202877]),
  array([0.14982801, 0.14539858, 0.14356844, 0.13871419, 0.13949263,
         0.14463507, 0.13836308])],)

# Price of Anarchy

## Waiting time
$$
    PoA_{waiting} = \frac{\max_{s \in E} W(s)}{\min_{s \in S} W(s)}
$$

In [10]:
get_price_of_anarchy(performance_measure_function=abg.markov.get_mean_waiting_time_using_markov_state_probabilities)

RuntimeError: generator raised StopIteration

## Blocking time
$$
    PoA_{blocking} = \frac{\max_{s \in E} B(s)}{\min_{s \in S} B(s)}
$$

In [11]:
get_price_of_anarchy(performance_measure_function=abg.markov.get_mean_blocking_time_using_markov_state_probabilities)

RuntimeError: generator raised StopIteration

## Proportion of individuals lost
$$
    PoA_{lost} = \frac{\max_{s \in E} P(L(s))}{\min_{s \in S} P(L(s))}
$$

In [12]:
get_price_of_anarchy(performance_measure_function=abg.markov.get_accepting_proportion_of_class_2_individuals)

RuntimeError: generator raised StopIteration